# -*- coding: utf-8 -*-
"""number of zeros at the end of factorial of a number x.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQ9Y4BNQyB6aoBMBzTsSRPZjRG0kx-L0
"""

#Find number of zeros at the end of factorial of a number x
x=int(input())
zeros=0
a=x
print("Find number of zeros at last of %d! ?" %x)
while(a>0):
  a=a//5
  zeros=zeros+a
print("Number of zeros at end of %d! are %d" %(x,zeros))

